version: "3.9"
networks:
  kiranroboshop:
    driver: bridge
services:
  web:
    image: "web:v1"
    container_name: web
    ports:
      - "80:80"
    depends_on:
    - catalogue
    - user
    - cart
    - payment


  mongodb:
    image: mongo:v1
    container_name: mongodb
  redis:
    image: redis
    container_name: redis
  catalogue:
    image: catalogue:v1
    container_name: catalogue
    depends_on:
    - mongodb
  user:
    image: user:v1
    container_name: user
    depends_on:
    - redis
    - mongodb
  cart:
    image: cart:v1
    container_name: cart
    depends_on:
    - redis
  rabbitmq:
    image: rabbitmq
    container_name: rabbitmq
  payment:
    image: payment:v1
    container_name: payment
    depends_on:
      - rabbitmq
  mysql:
    image: mysql
    container_name: mysql
  shipping:
    image: shipping:v1
    container_name: shipping
    depends_on:
    - mysql


