version: "3.9"
networks:
  kiranroboshop:
    driver: bridge
volumes:
  # this is equavlent to docker volume create name (named_volumes)
  mysql:
    driver: local
    driver_opts:
      o: bind
      type: none
      device: /home/ec2-user/mysql
  rabbitmq:
    driver: local
    driver_opts:
      o: bind
      type: none
      device: /home/ec2-user/rabbitmq
  mongo:
    driver: local
    driver_opts:
      o: bind
      type: none
      device: /home/ec2-user/mongo
  redis:
    driver: local
    driver_opts:
      o: bind
      type: none
      device: /home/ec2-user/redis
services:
  web:
    image: "web:v1"
    container_name: web
    ports:
      - "80:80"
    depends_on:
    - catalogue
    - user
    - cart
    - payment
    - shipping
    - ratings


  mongodb:
    image: mongo:v1
    container_name: mongodb
    volumes:
    - mongodb:/data/db
  redis:
    image: redis:v1
    container_name: redis
    volumes:
    - redis:/data
  catalogue:
    image: catalogue:v1
    container_name: catalogue
    depends_on:
    - mongodb
  user:
    image: user:v1
    container_name: user
    depends_on:
    - redis
    - mongodb
  cart:
    image: cart:v2
    container_name: cart
    depends_on:
    - redis
  rabbitmq:
    image: rabbitmq
    container_name: rabbitmq
    volumes:
    - rabbitmq:/var/lib/rabbitmq
  payment:
    image: payment:v1
    container_name: payment
    depends_on:
      - rabbitmq
  mysql:
    image: mysql:v1
    container_name: mysql
    volumes:
    - mysql:/var/lib/mysql
  shipping:
    image: shipping:v2
    container_name: shipping
    depends_on:
    - mysql
  ratings:
    image: ratings:v1
    container_name: ratings
    depends_on:
    - mysql


